name: Java Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          architecture: x64
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and package release
        run: mvn clean package -s ~/.m2/settings.xml -DskipTests -DskipITs -Dmaven.javadoc.skip=true

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.name }}
          draft: false
          prerelease: false

      - name: Upload artifacts to GitHub release
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: target/